testFilesMake:	testVectorsSetToledo.c testDivision.c testSquare.c
	gcc -Wall -pedantic -ansi testVectorsSetToledo.c -o testVectorsToledo.exe
	gcc -Wall -pedantic -ansi testDivision.c -o testsDivision.exe
	gcc -Wall -pedantic -ansi testSquare.c -o testModSquare.exe